name: Create Tag
on:
  workflow_call:
    inputs:
      version:
        description: "semver version to release: major, minor, patch"
        required: true
        default: "patch"
        type: string

jobs:
  CreateTag:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Main]
        with:
          fetch-depth: 0
          token: ${{ secrets.ANTI_PROTECTED_TOKEN }}
      - uses: volta-cli/action@v4
        with:
          package-json-path: "${{ github.workspace }}/package.json"
      - name: Install dependencies
        run: npm ci
      - name: Run commands in parallel
        run: |
          git config --global user.email 'infrastructure@smallstack.com'
          git config --global user.name 'Kleiner Sack'
          npm run release:${{inputs.version}}
